'use client'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { dispatchData, type EmailAnalytics, type EmailTotals } from '@/api/emailDispatches'
import Link from 'next/link'
import EmailDispatchReport from './EmailDispatchReport'

const names: Record<string, string> = { manual: 'Manual emails', newsletter: 'Newsletters', account: 'Automatic · account & security', application: 'Automatic · application confirmations', operations: 'Automatic · team operations', system: 'Other system emails', test: 'Test messages' }
const style = 'rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-blue-700'
export default function EmailAnalyticsView() {
  const [days, setDays] = useState('30')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')
  const [includeTests, setIncludeTests] = useState(false)
  const query = useQuery({ queryKey: ['email-analytics', days, from, to, includeTests], queryFn: () => {
    const params = new URLSearchParams({ days: days === 'custom' ? '30' : days, includeTests: String(includeTests) })
    if (days === 'custom') { params.set('from', from); params.set('to', to) }
    return dispatchData<EmailAnalytics>(`/analytics?${params}`)
  }, enabled: days !== 'custom' || Boolean(from && to), refetchInterval: (state) => state.state.data?.backlog.length ? 15000 : false })
  const daily = new Map<string, EmailTotals>()
  query.data?.daily.forEach((row) => { const previous = daily.get(row.day) || { accepted: 0, sent: 0, failed: 0, cancelled: 0, skipped: 0, retryAttempts: 0 }; Object.keys(previous).forEach((key) => { previous[key as keyof EmailTotals] += row[key as keyof EmailTotals] }); daily.set(row.day, previous) })
  return <section className="space-y-6">
    <div className="flex flex-wrap items-end gap-4"><label className="text-sm font-semibold">Reporting period<select className={`ml-2 ${style}`} value={days} onChange={(event) => setDays(event.target.value)}><option value="1">Today</option><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="custom">Custom range</option></select></label>{days === 'custom' && <><label className="text-sm">From <input className={style} type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-sm">To <input className={style} type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></>}<label className="flex gap-2 text-sm"><input type="checkbox" checked={includeTests} onChange={(event) => setIncludeTests(event.target.checked)} />Include test messages</label></div>
    {query.isPending && <p role="status">{days === 'custom' && !(from && to) ? 'Choose a start and end date.' : 'Loading email reporting…'}</p>}
    {query.isError && <p role="alert" className="text-red-700">{query.error.message} <button className={style} onClick={() => void query.refetch()}>Retry</button></p>}
    {query.data && <><p className="text-sm leading-6 text-slate-500">{query.data.definition} Reporting starts {query.data.reportingStartedAt ? new Date(query.data.reportingStartedAt).toLocaleDateString() : 'when the first available email is recorded'}. Dates use UTC. Anonymous totals last 365 days.</p><div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><caption className="p-4 text-left font-semibold text-slate-950">Email outcomes by source</caption><thead className="bg-slate-50 text-slate-600"><tr>{['Source', 'Accepted', 'Sent', 'Failed', 'Skipped', 'Cancelled'].map((text) => <th key={text} className="p-3">{text}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{Object.entries(query.data.totals).filter(([key]) => includeTests || key !== 'test').map(([key, value]) => <tr key={key}><th className="p-3 font-medium">{names[key] || key}</th>{(['accepted', 'sent', 'failed', 'skipped', 'cancelled'] as const).map((field) => <td key={field} className="p-3 tabular-nums">{value[field].toLocaleString()}</td>)}</tr>)}</tbody></table></div>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Current delivery backlog</h2><p className="mt-1 text-sm text-slate-500">Live workload, independent of the historical reporting period.</p><div className="mt-4 flex flex-wrap gap-8">{['scheduled', 'pending', 'processing', 'retry'].map((status) => <div key={status}><span className="text-sm text-slate-500">{{ scheduled: 'Scheduled', pending: 'Queued', processing: 'Processing', retry: 'Retrying' }[status]}</span><strong className="mt-1 block text-2xl tabular-nums">{query.data!.backlog.filter((row) => status === 'scheduled' ? row._id.scheduled : row._id.status === status && !row._id.scheduled).reduce((count, row) => count + row.count, 0)}</strong></div>)}</div></section>
      <div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><caption className="p-4 text-left font-semibold">Daily email trend</caption><thead className="bg-slate-50"><tr><th className="p-3">Date</th><th className="p-3">Accepted</th><th className="p-3">Sent</th><th className="p-3">Failed</th></tr></thead><tbody className="divide-y divide-slate-100">{[...daily].map(([day, totals]) => <tr key={day}><th className="p-3 font-normal">{day}</th><td className="p-3">{totals.accepted}</td><td className="p-3">{totals.sent}</td><td className="p-3">{totals.failed}</td></tr>)}{!daily.size && <tr><td colSpan={4} className="p-6 text-slate-500">No email activity in this period.</td></tr>}</tbody></table></div>
      <div className="overflow-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><caption className="p-4 text-left font-semibold">Template and audience breakdown</caption><thead className="bg-slate-50"><tr><th className="p-3">Template</th><th className="p-3">Audience</th><th className="p-3">Accepted</th><th className="p-3">Failures</th></tr></thead><tbody>{Object.values(query.data.daily.reduce<Record<string, { template: string; audience: string; accepted: number; failed: number }>>((all, row) => { const key = `${row.template}:${row.audience}`; const previous = all[key] || { template: row.template, audience: row.audience, accepted: 0, failed: 0 }; previous.accepted += row.accepted; previous.failed += row.failed; all[key] = previous; return all }, {})).map((row) => <tr key={`${row.template}:${row.audience}`} className="border-t border-slate-100"><td className="p-3">{row.template}</td><td className="p-3 capitalize">{row.audience}</td><td className="p-3">{row.accepted}</td><td className="p-3">{row.failed}</td></tr>)}</tbody></table></div>
      <EmailDispatchReport key={`${query.data.from}:${query.data.to}`} from={query.data.from} to={query.data.to} />
      <Link href="/admin-center/emails" className="inline-block text-sm font-semibold text-blue-800 underline underline-offset-4">Open the email centre →</Link>
    </>}
  </section>
}
