'use client'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { dispatchRequest, type Dispatch, type Delivery, type Paging } from '@/api/emailDispatches'
const button = 'rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-blue-700 disabled:opacity-50'
export default function EmailDispatchReport({ from, to }: { from: string; to: string }) {
  const [page, setPage] = useState(1)
  const [detail, setDetail] = useState<string | null>(null)
  const [detailPage, setDetailPage] = useState(1)
  const history = useQuery({ queryKey: ['broadcast-report', from, to, page], queryFn: () => dispatchRequest<{ data: Dispatch[]; pagination: Paging }>(`?acceptedOnly=true&from=${from}&to=${to}&page=${page}`), refetchInterval: (query) => query.state.data?.data.some((row) => ['queued', 'scheduled'].includes(row.state)) ? 10000 : false })
  const deliveries = useQuery({ queryKey: ['broadcast-report-deliveries', detail, detailPage], queryFn: () => dispatchRequest<{ data: Delivery[]; pagination: Paging }>(`/${detail}/deliveries?page=${detailPage}`), enabled: Boolean(detail), refetchInterval: (query) => query.state.data?.data.some((row) => ['pending', 'processing', 'retry'].includes(row.status)) ? 10000 : false })
  return <section className="space-y-5 rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-950">Manual dispatches</h2><p className="text-sm text-slate-500">Team, candidate, application messages and newsletters. Historical records are limited to the records available when reporting began.</p>
    {history.isPending && <p role="status">Loading dispatches…</p>}
    {history.isError && <p role="alert">Unable to load dispatches. <button className={button} onClick={() => void history.refetch()}>Retry</button></p>}
    <div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['Sender / template', 'Recipients', 'Delivery time', 'Progress', ''].map((label, index) => <th key={index} className="p-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{history.data?.data.map((row) => <tr key={row._id}><td className="p-3 font-medium">{row.ownerName || 'Team member'}<span className="mt-1 block text-xs font-normal text-slate-500">{row.template}</span></td><td className="p-3 tabular-nums">{row.recipientCount}<span className="block text-xs text-slate-500">{row.candidateCount} candidates · {row.teamCount} team</span></td><td className="p-3 text-slate-500">{new Date(row.scheduledFor || row.queuedAt || row.createdAt).toLocaleString('en-NG', { timeZone: 'UTC' })} UTC<span className="block capitalize">{row.state}</span></td><td className="p-3">{row.outcomes.sent} sent · {row.outcomes.dead} failed<span className="block text-xs text-slate-500">{row.live?.pending || 0} queued · {row.live?.processing || 0} processing · {row.live?.retry || 0} retrying</span><span className="block text-xs text-slate-500">{row.outcomes.skipped} skipped · {row.outcomes.cancelled} cancelled</span></td><td className="p-3"><button className={button} onClick={() => { setDetail(row._id); setDetailPage(1) }}>Delivery details</button></td></tr>)}{history.data && !history.data.data.length && <tr><td colSpan={5} className="p-6 text-slate-500">No accepted dispatches in this period.</td></tr>}</tbody></table></div>
    {history.data && <div className="flex items-center justify-between"><button className={button} disabled={!history.data.pagination.hasPreviousPage} onClick={() => setPage(page - 1)}>Previous dispatches</button><span className="text-sm">Page {page} of {history.data.pagination.totalPages}</span><button className={button} disabled={!history.data.pagination.hasNextPage} onClick={() => setPage(page + 1)}>Next dispatches</button></div>}
    {detail && <section className="border-t border-slate-200 pt-5"><div className="flex justify-between gap-4"><h3 className="font-semibold">30-day recipient details</h3><button className={button} onClick={() => setDetail(null)}>Close details</button></div>{deliveries.isPending && <p role="status">Loading recipient details…</p>}{deliveries.isError && <p role="alert">Unable to load recipient details. <button className={button} onClick={() => void deliveries.refetch()}>Retry</button></p>}<ul className="mt-4 divide-y divide-slate-100">{deliveries.data?.data.map((row) => <li key={row._id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{row.recipientLabel} · {row.recipient}</span><span className="capitalize">{row.status === 'dead' ? 'Failed' : row.status === 'pending' ? 'Queued' : row.status}</span></li>)}</ul>{deliveries.data && !deliveries.data.data.length && <p className="mt-4 text-sm text-slate-500">These individual delivery records have expired or are unavailable. The anonymous totals remain.</p>}{deliveries.data && <div className="mt-4 flex justify-between"><button className={button} disabled={!deliveries.data.pagination.hasPreviousPage} onClick={() => setDetailPage(detailPage - 1)}>Previous recipients</button><button className={button} disabled={!deliveries.data.pagination.hasNextPage} onClick={() => setDetailPage(detailPage + 1)}>Next recipients</button></div>}</section>}
  </section>
}
